### ISSUE TITLE
Recent GitHub Web Hook Deliveries - Internal Server Error

### ISSUE THREAD

**Issue by suriyaa** [parkr/archivist#1]
Hello @parkr,

I'm using the Archivist software for my organization called "@Bunto". I published the project with my required env variables to Heroku successfully:

![Heroku Dashboard Settings of "bunto-archivist"](https://cloud.githubusercontent.com/assets/5073946/16170396/7d48351e-3551-11e6-954c-b1fe6d0c7b7e.png)

---

I tried now to set the Web Hooks (https://github.com/parkr/archivist#usage) but I get an 500 error:

![GitHub WebHook - https://bunto-archivist.herokuapp.com - github.com/organizations/bunto/settings/hooks/8804790#delivery-res | Screenshot made by Suriyaa](https://cloud.githubusercontent.com/assets/5073946/16170343/df079c60-354f-11e6-9882-7b9d8fe9f107.png)

> What should I do?
- Imported your repo to repo: https://github.com/buntobot/archivist
- Heroku App Website: https://bunto-archivist.herokuapp.com/

_Yours,_
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by parkr** [comment]
Hey Suriyaa, I am not sure if this works anymore. I don't use this for anything at this time so it may need work.

Check your Heroku logs to see what the error is. It may only accept certain payloads so the initial "ping" event may cause it to fail.

Sorry I can't help you more! I'll update the repo to indicate that it is no longer maintained.
